### ISSUE TITLE
API upload missing

### ISSUE THREAD

**Issue by dangviettuan** [jadolg/rocketchat_API#18] opened 2018-03-26 15:02 UTC
API https://rocket.chat/docs/developer-guides/rest-api/rooms/upload/ is missing.

**Comment by jadolg** [comment] 2018-03-26 15:45
Will implement this ASAP. There are some missing endpoints I still have to implement. They should be here soon.

**Comment by dangviettuan** [comment] 2018-03-27 03:00
I'm working around this API, in my case if I upload and UTF-8 file name (Japanese), in Rocket Chat I receive an strange characters like  �����.png

**Comment by jadolg** [comment] 2018-03-27 14:38
Can you try after this commit https://github.com/jadolg/rocketchat_API/commit/ea211acad0d1981821a25b82f195976f3b9b86f8 ?
New version is already published.

**Comment by dangviettuan** [comment] 2018-03-28 04:42
File uploaded but after click down load I receive and �����.png.txt file. (filename is in Japanese)
I had faced with this issued, my solution is use requests_toolbelt to encode a multipart form, the file were uploaded right extension but strange name still exit.

**Comment by BuZZ-dEE** [comment] 2018-04-12 23:30
Upload does not work for me using the following method.:

```python
    def rooms_upload(self, rid, file, **kwargs):
        """Post a message with attached file to a dedicated room."""
        files = {
            'file': open(file, 'rb')
        }
        return self.__call_api_post('rooms.upload/' + rid, kwargs=kwargs, use_json=False, files=files)
```
I use the following code to call the upload function.:

```python
    def send_zipped_log(self, log_file):
        zipped_log = zipfile.ZipFile('log.zip', mode='w')
        try:
            try:
                import zlib
                compression = zipfile.ZIP_DEFLATED
            except:
                compression = zipfile.ZIP_STORED
            zipped_log.write(log_file, compress_type=compression)
        finally:
            zipped_log.close()
        
        response = self.rocket.rooms_upload(self.config['room_id'], zipped_log.filename)
        os.remove(zipped_log.filename)
```

I get the response:

```
{"success":false,"error":"Invalid room [error-invalid-room]","errorType":"error-invalid-room"}
```

But the following function does work.:

```python
    def chat_post_message(self, text, room_id=None, channel=None, **kwargs):
        """Posts a new chat message."""
        if room_id:
            return self.__call_api_post('chat.postMessage', roomId=room_id, text=text, kwargs=kwargs)
        elif channel:
            return self.__call_api_post('chat.postMessage', channel=channel, text=text, kwargs=kwargs)
        else:
            raise RocketMissingParamException('roomId or channel required')
```

**Comment by jadolg** [comment] 2018-05-12 20:51
@dangviettuan after I tested with curl the error disappears so seems to be a python unicode problem. I'm currently working on it.

@BuZZ-dEE post message accept both room id or name but upload only accepts room id. Are you using the room id or the name?

**Comment by jadolg** [comment] 2018-05-12 21:14
@dangviettuan seems that the problem is a little bit deeper than my library. There is a problem in the requests library https://github.com/requests/requests/issues/3446about this and it falls back into a urllib3 problem https://github.com/urllib3/urllib3/pull/856 
I'll keep an eye on it but in the meantime should find a workaround.

**Comment by BuZZ-dEE** [comment] 2018-05-15 00:36
@jadolg i use the channel name.

**Comment by jadolg** [comment] 2018-10-16 22:39
I'm still not finding a good way to do this. this one up there did not solve the issue for me :(
I'll need help to solve it

**Comment by dangviettuan** [comment] 2018-10-19 04:38
@jadolg can you describe more about your issue?

**Comment by dangviettuan** [comment] 2018-10-20 14:44
In #18 comment, I have a Django API to forward the upload file to RocketChat -> the file is from the request. If you wanna to implement a function for this lib, I think we just put the file as a fuction param. Ex: UploadFile(file, ....) and wrap my code to this fuction. After that, replace 'request.data['file']' in my code with 'file' param.

**Comment by jadolg** [comment] 2018-10-22 16:53
@dangviettuan yes, I tried changing the encoding as you did and file got uploaded but problems remained. I don't remember if I even pushed it :'(

**Comment by dangviettuan** [comment] 2018-10-25 02:58
@jadolg can you share the source code? Hope I can help 😄

**Comment by jadolg** [comment] 2018-10-25 14:14
@dangviettuan it seems that I trashed it since it was bigger than the one I'm using and the result is the same. Could you check the current method?

**Comment by jadolg** [comment] 2020-05-28 09:47
I can not reproduce this problem anymore.
![image](https://user-images.githubusercontent.com/5427672/83126314-f01c7b80-a0d8-11ea-9efb-9d0d064ab959.png)
The á character used to be problematic here because of encoding but the problem it's gone.
I'll close the issue now.

**Closed by jadolg** 2020-05-28 09:47 UTC
Labels: enhancement, help wanted, no-issue-activity
