### ISSUE TITLE
ImportError: cannot import name 'RocketMissingParamException' after upgrade in pip

### ISSUE THREAD

**Issue by cesarandreslopez** [jadolg/rocketchat_API#20] opened 2018-04-25 17:06 UTC
Hello!

After using this Python Wrapper for a while during several months without issues I find that after updating today using 

``pip install rocketchat_API --upgrade``

I get:

```
File "xxxx.py", line 13, in <module>
from rocketchat_API.rocketchat import RocketChat
File "/usr/local/lib/python3.6/site-packages/rocketchat_API/rocketchat.py", line 5, in <module>
from rocketchat_API.APIExceptions.RocketExceptions import RocketConnectionException, RocketAuthenticationException, \
ImportError: cannot import name 'RocketMissingParamException'
```
In:
Python version: 3.6.4 (default, Dec 21 2017, 01:29:34)  [GCC 6.3.0 20170516]

Same identical source code and enviroment was working till today after this upgrade.

Any tips?

**Comment by jadolg** [comment] 2018-04-26 22:37
hi @cesarandreslopez, can you share the version you updated to?

**Comment by kbojens** [comment] 2018-04-27 08:14
I can confirm the exact same error with a fresh install of Version „rocketchat-API (0.6.8)”:

` Traceback (most recent call last):
  File "./foobar.py", line 4, in <module>
    from rocketchat_API.rocketchat import RocketChat
  File "/usr/local/lib/python3.5/dist-packages/rocketchat_API/rocketchat.py", line 5, in <module>
    from rocketchat_API.APIExceptions.RocketExceptions import RocketConnectionException, RocketAuthenticationException, \
ImportError: cannot import name 'RocketMissingParamException' `

**Comment by Bart274** [comment] 2018-05-02 10:54
is there any solution for this issue?

**Comment by cesarandreslopez** [comment] 2018-05-02 11:42
@Bart274 while this gets resolved on the most recent version you can do:

` pip install rocketchat_API==0.6.7`

**Comment by jadolg** [comment] 2018-05-02 16:49
Sorry for the delay in my answer. I'm working on it but I'm having serious internet connection issues. The only thing that changed from the previous version is that I was trying to show markdown description on the new pypi so I added this line `long_description_content_type="text/markdown"` to setup.py and uploaded using `python setup.py bdist_wheel upload`.

**Comment by jadolg** [comment] 2018-05-02 17:12
well, I installed the wheel on a clean environment (from my harddrive, not from internet) and seems to be working perfect. This is what's installed on the environment:
```certifi==2017.7.27.1
chardet==3.0.4
idna==2.6
requests==2.18.4
rocketchat-API==0.6.8
urllib3==1.22
```
and this is the code I tried:
```from pprint import pprint

from rocketchat_API.rocketchat import RocketChat

rocket = RocketChat('user', 'password')
pprint(rocket.channels_list_joined().json())
```

**Comment by jadolg** [comment] 2018-05-02 17:15
Now I installed from internet and I'm getting the same error as you. I think this might be related with the new PyPi and the way I uploaded my package.

**Comment by jadolg** [comment] 2018-05-02 17:41
Well, seems that the problem was related to the way I was packaging/uploading to new PyPi. It does not seem to be compatible with good old `python setup.py bdist_wheel upload`. I uploaded a new version using Twine and it's working fine for me. Can anyone confirm after installing 0.6.9 ?

**Comment by jadolg** [comment] 2018-05-03 15:48
perfect! I will close this issue then. Thanks for your cooperation and support @all :)

**Closed by jadolg** 2018-05-03 15:48 UTC
Labels: bug, packaging
